name: Unity Test and Build
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Unity
        uses: game-ci/setup-unity@v1
        with:
          unity-version: 2020.3.14f1
          components: unity-webgl
      - name: Cache Unity Packages
        uses: actions/cache@v2
        with:
          path: Library
          key: ${{ runner.os }}-unity-${{ hashFiles('**/ProjectSettings/ProjectVersion.txt') }}
          restore-keys: ${{ runner.os }}-unity-
      # - name: Run Tests
        # run: |
        #   /opt/unity/Editor/Unity \
        #   -batchmode \
        #   -nographics \
        #   -projectPath ${{ github.workspace }}/TestRunnerGame \
        #   -runTests \
        #   -testPlatform editmode \
        #   -testResults ${{ github.workspace }}/test_results.xml
      - name: Build WebGL
        run: |
          /opt/unity/Editor/Unity \
          -batchmode \
          -nographics \
          -quit \
          -projectPath ${{ github.workspace }}/TestRunnerGame \
          -executeMethod BuildScript.BuildWebGL \
          -logFile WebGLBuild.log
