name: Build WebGL

on:
  push:
    branches: [ main ]

jobs:
    buildForAllSupportedPlatforms:
        name: Build for ${{ matrix.targetPlatform }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                projectPath:
                    - TestRunnerGame
                targetPlatform:
                    - WebGL

        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  lfs: true
            - name: Cache
              uses: actions/cache@v2
              with:
                  path: ${{ matrix.projectPath }}/Library
                  key: Library-${{ matrix.targetPlatform }}
                  restore-keys: Library-
            - name: Build
              uses: game-ci/unity-builder@v2
              env:
                  UNITY_LICENSE: ${{ secrets.UNITY_SERIAL }}
              with:
                  targetPlatform: ${{ matrix.targetPlatform }}
                  projectPath: ${{ matrix.projectPath }}/
            - name: Storing Artifact
              uses: actions/upload-artifact@v2
              with:
                  name: Build-${{ matrix.targetPlatform }}
                  path: build/${{ matrix.targetPlatform }}